export const countryData = {
  AF: { name: 'Afghanistan', code: '+93' },
  AL: { name: 'Albania', code: '+355' },
  DZ: { name: 'Algeria', code: '+213' },
  AS: { name: 'American Samoa', code: '+1684' },
  AD: { name: 'Andorra', code: '+376' },
  AO: { name: 'Angola', code: '+244' },
  AI: { name: 'Anguilla', code: '+1264' },
  AG: { name: 'Antigua and Barbuda', code: '+1268' },
  AR: { name: 'Argentina', code: '+54' },
  AM: { name: 'Armenia', code: '+374' },
  AU: { name: 'Australia', code: '+61' },
  AT: { name: 'Austria', code: '+43' },
  AZ: { name: 'Azerbaijan', code: '+994' },
  BS: { name: 'Bahamas', code: '+1242' },
  BH: { name: 'Bahrain', code: '+973' },
  BD: { name: 'Bangladesh', code: '+880' },
  BB: { name: 'Barbados', code: '+1246' },
  BY: { name: 'Belarus', code: '+375' },
  BE: { name: 'Belgium', code: '+32' },
  BZ: { name: 'Belize', code: '+501' },
  BJ: { name: 'Benin', code: '+229' },
  BM: { name: 'Bermuda', code: '+1441' },
  BT: { name: 'Bhutan', code: '+975' },
  BO: { name: 'Bolivia', code: '+591' },
  BA: { name: 'Bosnia and Herzegovina', code: '+387' },
  BR: { name: 'Brazil', code: '+55' },
  BN: { name: 'Brunei', code: '+673' },
  BG: { name: 'Bulgaria', code: '+359' },
  CA: { name: 'Canada', code: '+1' },
  CN: { name: 'China', code: '+86' },
  CO: { name: 'Colombia', code: '+57' },
  CZ: { name: 'Czech Republic', code: '+420' },
  DK: { name: 'Denmark', code: '+45' },
  EG: { name: 'Egypt', code: '+20' },
  FI: { name: 'Finland', code: '+358' },
  FR: { name: 'France', code: '+33' },
  DE: { name: 'Germany', code: '+49' },
  GR: { name: 'Greece', code: '+30' },
  HK: { name: 'Hong Kong', code: '+852' },
  IN: { name: 'India', code: '+91' },
  ID: { name: 'Indonesia', code: '+62' },
  IE: { name: 'Ireland', code: '+353' },
  IL: { name: 'Israel', code: '+972' },
  IT: { name: 'Italy', code: '+39' },
  JP: { name: 'Japan', code: '+81' },
  KR: { name: 'South Korea', code: '+82' },
  MY: { name: 'Malaysia', code: '+60' },
  MX: { name: 'Mexico', code: '+52' },
  NL: { name: 'Netherlands', code: '+31' },
  NZ: { name: 'New Zealand', code: '+64' },
  NO: { name: 'Norway', code: '+47' },
  PK: { name: 'Pakistan', code: '+92' },
  PH: { name: 'Philippines', code: '+63' },
  PL: { name: 'Poland', code: '+48' },
  PT: { name: 'Portugal', code: '+351' },
  RU: { name: 'Russia', code: '+7' },
  SA: { name: 'Saudi Arabia', code: '+966' },
  SG: { name: 'Singapore', code: '+65' },
  ZA: { name: 'South Africa', code: '+27' },
  ES: { name: 'Spain', code: '+34' },
  SE: { name: 'Sweden', code: '+46' },
  CH: { name: 'Switzerland', code: '+41' },
  TW: { name: 'Taiwan', code: '+886' },
  TH: { name: 'Thailand', code: '+66' },
  TR: { name: 'Turkey', code: '+90' },
  AE: { name: 'United Arab Emirates', code: '+971' },
  GB: { name: 'United Kingdom', code: '+44' },
  US: { name: 'United States', code: '+1' },
  VN: { name: 'Vietnam', code: '+84' },
};

export type CountryCode = keyof typeof countryData;
